name: CI - Chapter 08

on:
  push:
    branches: [ main, master ]
    paths:
      - 'chapter08/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'chapter08/**'
  # 手動実行を可能にする
  workflow_dispatch:
    inputs:
      reason:
        description: '実行理由（任意）'
        required: false
        default: '手動実行'

jobs:
  test:
    name: Test - Chapter 08
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./chapter08
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test
    
    - name: Run E2E tests
      if: runner.os == 'macos-latest'
      run: npm run test:e2e
    
  build:
    name: Build - Chapter 08
    needs: test
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: macos-latest
            artifact_name: mac
            build_script: dist:mac
          - os: windows-latest
            artifact_name: windows
            build_script: dist:win
          - os: ubuntu-latest
            artifact_name: linux
            build_script: dist:linux
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./chapter08
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run ${{ matrix.build_script }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: electron-app-${{ matrix.artifact_name }}
        path: |
          chapter08/release/*
          !chapter08/release/*.blockmap
          !chapter08/release/*.yml
    
    - name: Upload release
      if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
      uses: softprops/action-gh-release@v2
      with:
        files: |
          chapter08/release/*
          !chapter08/release/*.blockmap
          !chapter08/release/*.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
